version: '3.3'

services: 
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: server-app
    container_name: express-server
    command: yarn start
    volumes: 
       - ./server/:/usr/src/app
       - /usr/src/app/node_modules
    ports: 
      - "8080:8080"
    depends_on: 
      - mongo
    env_file: ./server/.env
    environment: 
      - NODE_ENV=development
    networks: 
      - app-network

  mongo:
    image: mongo:latest
    volumes: 
      - data-volume:/data/db
    ports: 
      - "27017:27017"
    networks:
      - app-network

  client:
    build: 
      context: ./dashboard-admin
      dockerfile: Dockerfile
    image: admin-dashboard-app
    container_name: react-dashboard
    command: yarn start
    volumes: 
      - ./dashboard/:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - server
    ports:
      - "3000:3000"
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge
  
volumes: 
  data-volume:
  node_modules:
  web-root:
    driver: local
    