export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'

export const POST_ARTICLE = 'POST_ARTICLE'
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'

export const EDIT_ARTICLE = 'EDIT_ARTICLE'
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'

export const ARTICLE_FAIL = 'ARTICLE_FAIL'
