export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'

export const POST_CATEGORY = 'POST_CATEGORY'
export const POST_CATEGORY_SUCESS = 'POST_CATEGORY_SUCCESS'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'

export const CATEGORY_FAIL = 'CATEGORY_FAIL'
