export const GET_USERS = 'GET_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

export const GET_USERS_DATA = 'GET_USERS_DATA'
export const GET_USERS_DATA_SUCCESS = 'GET_USERS_DATA_SUCCESS'

export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const USERS_FAIL = 'USERS_FAIL'
